# Generated by Django 3.0.6 on 2022-01-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='timeline',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
