# Generated by Django 3.0.6 on 2022-01-08 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='Teams')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank='True', related_name='team_members', to='api.Profile')),
                ('projects', models.ManyToManyField(blank=True, related_name='team_projects', to='api.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='jobs')),
                ('title', models.CharField(max_length=255)),
                ('max_personel', models.PositiveIntegerField(default=0)),
                ('min_personel', models.PositiveIntegerField(default=0)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_rank', to='api.Rank')),
            ],
        ),
    ]
