# Generated by Django 3.1 on 2022-06-25 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220625_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='project',
            new_name='projects',
        ),
    ]
