# Generated by Django 3.0.6 on 2022-01-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_job_rank_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='rank',
            field=models.CharField(choices=[('Class D', '4'), ('Class C', '3'), ('Class B', '2'), ('Class A', '1'), ('Class S', '0')], max_length=255),
        ),
    ]
