# Generated by Django 3.0.6 on 2022-01-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220108_1748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.CharField(choices=[('4', 'Class D'), ('3', 'Class C'), ('2', 'Class B'), ('1', 'Class A'), ('0', 'Class S')], default='4', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='rank',
            field=models.CharField(choices=[('4', 'Class D'), ('3', 'Class C'), ('2', 'Class B'), ('1', 'Class A'), ('0', 'Class S')], default='4', max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='rank',
            field=models.CharField(choices=[('4', 'Class D'), ('3', 'Class C'), ('2', 'Class B'), ('1', 'Class A'), ('0', 'Class S')], default='4', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='rank',
            field=models.CharField(choices=[('4', 'Class D'), ('3', 'Class C'), ('2', 'Class B'), ('1', 'Class A'), ('0', 'Class S')], default='4', max_length=255),
        ),
    ]
