# Generated by Django 3.2.3 on 2022-09-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
