# Generated by Django 3.2.15 on 2022-09-25 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_servicerequest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.ForeignKey(default='6', on_delete=django.db.models.deletion.DO_NOTHING, related_name='profileranks', to='api.rank'),
        ),
    ]
