# Generated by Django 3.2.15 on 2022-09-26 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_profile_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profileranks', to='api.rank'),
        ),
    ]
