# Generated by Django 4.1.6 on 2023-03-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Profiles", "0003_alter_profile_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/profile/"),
        ),
    ]
