# Generated by Django 4.1.7 on 2023-03-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0005_driver_application'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Driver_Application',
            new_name='Application',
        ),
        migrations.RenameModel(
            old_name='Account',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='account_type',
            new_name='Class',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_driver',
        ),
    ]
