# Generated by Django 4.1.7 on 2023-03-20 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ranks', '0001_initial'),
        ('Profiles', '0007_delete_class_alter_profile_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_rank', to='Ranks.rank'),
            preserve_default=False,
        ),
    ]
