# Generated by Django 4.1.7 on 2023-03-20 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Class", "0001_initial"),
        ("Profiles", "0008_profile_rank"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_granted", models.BooleanField(default=False)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "Class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Class.class"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Profiles.profile",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Application",
        ),
    ]
