# Generated by Django 4.1.7 on 2023-03-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Profiles", "0009_classapplication_delete_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="balance",
            field=models.IntegerField(default=0),
        ),
    ]
