# Generated by Django 4.1.7 on 2023-03-20 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Class", "0001_initial"),
        ("Profiles", "0011_profile_xp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="Class",
        ),
        migrations.AddField(
            model_name="profile",
            name="Class",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="Class.class"
            ),
            preserve_default=False,
        ),
    ]
