# Generated by Django 4.1.7 on 2023-03-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Profiles", "0009_classapplication_delete_application"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="default.png", upload_to="events"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(max_length=255)),
                ("date_time", models.DateTimeField()),
                ("is_active", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                (
                    "attendants",
                    models.ManyToManyField(
                        blank=True, related_name="participants", to="Profiles.profile"
                    ),
                ),
            ],
        ),
    ]
