# Generated by Django 4.1.7 on 2023-03-20 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Profiles", "0009_classapplication_delete_application"),
        ("Events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="attendants",
        ),
        migrations.AddField(
            model_name="event",
            name="has_ended",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_present", models.BooleanField(default=False)),
                ("clocked_in_at", models.TimeField(auto_now=True)),
                ("clocked_out_at", models.TimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Events.event"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Profiles.profile",
                    ),
                ),
            ],
        ),
    ]
