# Generated by Django 3.1 on 2022-06-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220625_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='members', to='api.Project'),
        ),
    ]
