# Generated by Django 3.2.3 on 2022-07-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220625_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answered_by',
        ),
    ]
