# Generated by Django 3.2.15 on 2022-09-24 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_client_jobrequest_note_service_servicerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='notes',
        ),
        migrations.AddField(
            model_name='note',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Service_notes', to='api.service'),
            preserve_default=False,
        ),
    ]
