# Generated by Django 3.2.15 on 2022-09-24 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220924_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='personnels',
        ),
    ]
