# Generated by Django 3.2.15 on 2022-09-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_servicerequest_personnels'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='image',
            field=models.ImageField(default='default.png', upload_to='serviceRequests'),
        ),
    ]
