# Generated by Django 4.1.7 on 2023-03-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0012_remove_profile_class_profile_class'),
        ('Chat', '0003_rename_user_post_creator_forum_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(related_name='rooms', to='Profiles.profile'),
        ),
    ]
