# Generated by Django 4.1.7 on 2023-03-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0012_remove_profile_class_profile_class'),
        ('Chat', '0004_alter_room_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(to='Profiles.profile'),
        ),
    ]
