# Generated by Django 4.1.7 on 2023-03-20 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Profiles", "0009_classapplication_delete_application"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=20)),
                ("reference", models.CharField(max_length=200)),
                ("amount", models.PositiveIntegerField(default=0)),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "reciever",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reciever",
                        to="Profiles.profile",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sender",
                        to="Profiles.profile",
                    ),
                ),
            ],
        ),
    ]
