# Generated by Django 4.1.7 on 2023-03-20 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Ranks", "0002_rank_tag_alter_rank_title"),
        ("Missions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mission",
            name="ranks",
        ),
        migrations.AddField(
            model_name="mission",
            name="rank",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="Ranks.rank"
            ),
            preserve_default=False,
        ),
    ]
