# Generated by Django 4.1.7 on 2023-03-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Missions", "0002_remove_mission_ranks_mission_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="xp",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
